name: Update themes
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
env:
  HUGO_VERSION: "v0.119.0"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.21.0"
      - name: Update submodules
        shell: bash
        working-directory: ./cmd/hugothemesitebuilder
        run: |
          go run main.go build -configOnly
          cd build
          git config --global user.email "bep@users.noreply.github.com"
          git config --global user.name "bep"
          go install github.com/gohugoio/hugo@${{ env.HUGO_VERSION }}
          hugo mod get
          git add .
          git commit -am "[Bot] Update themes"
          git push --force-with-lease
